name = "animecurio"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "animecurio-db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
